const actionTypes = Object.freeze({
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIL: 'FETCH_POSITION_FAIL',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAIL: 'FETCH_ALL_USERS_FAIL',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',

    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAIL: 'FETCH_TOP_DOCTOR_FAIL',
    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAIL: 'FETCH_ALL_DOCTORS_FAIL',
    POST_DETAIL_DOCTORS_SUCCESS: 'POST_DETAIL_DOCTORS_SUCCESS',
    POST_DETAIL_DOCTORS_FAIL: 'POST_DETAIL_DOCTORS_FAIL',
    GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_FAIL: 'GET_DETAIL_DOCTOR_FAIL',
    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAIL: 'FETCH_ALLCODE_SCHEDULE_TIME_FAIL',
    FETCH_REQUIRED_DOCTOR_INFOR_START: 'FETCH_REQUIRED_DOCTOR_INFOR_START',
    FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFOR_FAIL: 'FETCH_REQUIRED_DOCTOR_INFOR_FAIL',

    FETCH_ALL_SPECIALTY_SUCCESS: 'FETCH_ALL_SPECIALTY_SUCCESS',
    FETCH_ALL_SPECIALTY_FAIL: 'FETCH_ALL_SPECIALTY_FAIL',
    FETCH_DETAIL_SPECIALTY_SUCCESS: 'FETCH_DETAIL_SPECIALTY_SUCCESS',
    FETCH_DETAIL_SPECIALTY_FAILD: 'FETCH_DETAIL_SPECIALTY_FAILD',
    FETCH_DETAIL_CLINIC_SUCCESS: 'FETCH_DETAIL_CLINIC_SUCCESS',
    FETCH_DETAIL_CLINIC_FAILD: 'FETCH_DETAIL_CLINIC_FAILD',
    FETCH_ALL_CLINICS_SUCCESS: 'FETCH_ALL_CLINICS_SUCCESS',
    FETCH_ALL_CLINICS_FAILED: 'FETCH_ALL_CLINICS_FAILED',
    FETCH_ALL_HANDBOOKS_SUCCESS: 'FETCH_ALL_HANDBOOKS_SUCCESS',
    FETCH_ALL_HANDBOOKS_FAILED: 'FETCH_ALL_HANDBOOKS_FAILED',
    FETCH_DETAIL_HANDBOOK_SUCCESS: 'FETCH_DETAIL_HANDBOOK_SUCCESS',
    FETCH_DETAIL_HANDBOOK_FAILED: 'FETCH_DETAIL_HANDBOOK_FAILED',

    GET_ALL_APPOINTMENTS_BY_ID_SUCCESS: 'GET_ALL_APPOINTMENTS_BY_ID_SUCCESS',
    GET_ALL_APPOINTMENTS_BY_ID_FAIL: 'GET_ALL_APPOINTMENTS_BY_ID_FAIL',
    FETCH_HISTORY_APPOINTMENT_SUCCESS: 'FETCH_HISTORY_APPOINTMENT_SUCCESS',
    FETCH_HISTORY_APPOINTMENT_FAILED: 'FETCH_HISTORY_APPOINTMENT_FAILED',
    SAVE_BOOKING_DATA_SUCCESS: 'SAVE_BOOKING_DATA_SUCCESS',
    SAVE_BOOKING_DATA_FAILD: 'SAVE_BOOKING_DATA_FAILD',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',

    // Chatbot / AI support
    UPDATE_CHAT_HISTORY: 'UPDATE_CHAT_HISTORY',
    CLEAR_CHAT_HISTORY: 'CLEAR_CHAT_HISTORY',
    POST_CHAT_WITH_AI_FAIL: 'POST_CHAT_WITH_AI_FAIL',
    CHAT_AI_RESPONSE_START: 'CHAT_AI_RESPONSE_START',
    CHAT_AI_RESPONSE_CHUNK: 'CHAT_AI_RESPONSE_CHUNK',
    CHAT_AI_RESPONSE_DONE: 'CHAT_AI_RESPONSE_DONE',
    CHAT_AI_SET_TYPING: 'CHAT_AI_SET_TYPING',

    FETCH_CHAT_SESSIONS_SUCCESS: 'FETCH_CHAT_SESSIONS_SUCCESS',
    FETCH_CHAT_SESSIONS_FAIL: 'FETCH_CHAT_SESSIONS_FAIL',
    FETCH_CHAT_HISTORY_SUCCESS: 'FETCH_CHAT_HISTORY_SUCCESS',
    FETCH_CHAT_HISTORY_FAIL: 'FETCH_CHAT_HISTORY_FAIL',

    // Socket/Realtime Core
    SOCKET_CONNECT: 'SOCKET_CONNECT',
    SOCKET_DISCONNECT: 'SOCKET_DISCONNECT',
    SOCKET_SET_INSTANCE: 'SOCKET_SET_INSTANCE',

    NOTIFICATION_ADD: 'NOTIFICATION_ADD',
    NOTIFICATION_CLEAR: 'NOTIFICATION_CLEAR',
    USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',

    REGISTER_INITIATE_SUCCESS: 'REGISTER_INITIATE_SUCCESS',
    REGISTER_INITIATE_FAIL: 'REGISTER_INITIATE_FAIL',
    REGISTER_SET_SESSION: 'REGISTER_SET_SESSION',
    REGISTER_CLEAR_SESSION: 'REGISTER_CLEAR_SESSION'
});

export default actionTypes;
